version: '3.7'
services:
  ohou-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/ohou-frontend/node_modules
      - .:/app/ohou-frontend
    ports:
      - '80:80'
